- id: '1587261294860'
  alias: Close Garage Door
  description: Close garage door when alarm set to home or away
  trigger:
  - platform: state
    entity_id: alarm_control_panel.north_york_alarm
    to: armed_home
  condition:
  - condition: state
    entity_id: cover.garage
    state: open
  action:
  - data: {}
    service: cover.close_cover
    target:
      entity_id: cover.garage
  mode: single
- id: '1593321973249'
  alias: Outside Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.backyard_2
      - light.frontyard_2
  - type: turn_on
    device_id: 5170777a6dc3c2c8be39a8aa60b32bbd
    entity_id: switch.plug1
    domain: switch
  mode: single
- id: '1596602195449'
  alias: Goodnight
  description: Turn outside lights off when alarm is set to home
  trigger:
  - platform: state
    entity_id: alarm_control_panel.north_york_alarm
    to: armed_home
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.backyard_2
      - light.frontyard_2
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.plug1
      - switch.living_room_lamp
  mode: single
- id: '1611716087928'
  alias: Bar Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.living_room_lamp
  mode: single
- id: '1616129428006'
  alias: FrontDoorAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_motion_2
  condition: []
  action:
  - service: image_processing.scan
    target:
      entity_id: image_processing.deepstack_object_front_door
  mode: single
  max: 10
- id: '1616170339677'
  alias: GarageAI
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.garage_motion
  condition: []
  action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.deepstack_object_garage
  mode: parallel
  max: 10
- id: '1616212788722'
  alias: Motioneye - Sidegate - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard-started
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sidegate_motion_detected
  mode: single
- id: '1616212897306'
  alias: Motioneye - Sidegate - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard-ended
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sidegate_motion_detected
  mode: queued
  max: 10
- id: '1616214454392'
  alias: SidegateAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sidegate_motion
  condition: []
  action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.deepstack_object_sidegate
  mode: queued
  max: 10
- id: '1617115271505'
  alias: Motioneye - Garage - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-garage-started
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_motion_detected
  mode: single
- id: '1617115348817'
  alias: Motioneye - Garage - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-garage-ended
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_motion_detected
  mode: single
- id: '1625357005839'
  alias: Turn Outside Lights Off If Alarm Away
  description: ''
  trigger:
  - platform: device
    device_id: 9a05613f3a33aeeb14ee15755b521bb9
    domain: alarm_control_panel
    entity_id: alarm_control_panel.north_york_alarm
    type: armed_away
  condition:
  - condition: time
    before: 00:00:00
    after: '22:30:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.frontyard
      - light.backyard
    data: {}
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.plug1
      - switch.living_room_lamp
  mode: single
- id: '1627317239944'
  alias: Turn HVAC off when doors remain open
  description: Set the Nest thermostat to 'Eco' mode when either the front door or
    back door is opened for more than 5 minutes.
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
    for: 00:10:00
  - platform: state
    entity_id: binary_sensor.back_door
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.main_floor
  mode: single
- id: '1629773116634'
  alias: BackdoorAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.backdoor_motion
  condition: []
  action:
  - service: image_processing.scan
    target:
      entity_id: image_processing.deepstack_object_backdoor
    data: {}
  mode: queued
  max: 10
- id: '1629773270589'
  alias: Motioneye - Backdoor - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard2-started
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.backdoor_motion_detected
  mode: single
- id: '1629773461364'
  alias: Motioneye - Backdoor - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard2-ended
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.backdoor_motion_detected
  mode: queued
  max: 10
- id: '1635131985239'
  alias: HA_Backup_To_GitHub
  description: push HA configuration to GitHub repo
  trigger:
  - platform: time
    at: '23:23:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/ha_gitpush.sh
  mode: single
- id: '1643859086086'
  alias: Nigel_Work_Start
  description: Turn basement lights on if Nigel at home during weekday.
  trigger:
  - platform: time
    at: 08:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: '17:00:00'
    after: 08:00:00
  - condition: state
    state: home
    entity_id: device_tracker.damngenius_2
  action:
  - scene: scene.basementlights
  mode: single
- id: '1652139604169'
  alias: Nigel_Work_End
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
    enabled: true
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 300
    target:
      area_id: office
  mode: single
- id: '1673200577304'
  alias: Basement Motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.basementlights
    state: 'off'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.basementlights
    metadata: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.basement_off
    metadata: {}
  mode: single
