- id: '1593321973249'
  alias: Outside Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.outdoorlights
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.plug1
      - switch.living_room_lamp
  mode: single
- id: '1596602195449'
  alias: Goodnight
  description: Turn outside lights off when alarm is set to home
  trigger:
  - platform: state
    entity_id: alarm_control_panel.north_york_alarm
    to: armed_home
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.backyard_2
      - light.frontyard_2
      - light.basementlights
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.plug1
      - switch.living_room_lamp
  mode: single
- id: '1611716087928'
  alias: Bar Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.living_room_lamp
  mode: single
- id: '1616129428006'
  alias: FrontDoorAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_motion_2
  condition: []
  action:
  - service: image_processing.scan
    target:
      entity_id: image_processing.deepstack_object_front_door
  mode: single
  max: 10
- id: '1616170339677'
  alias: GarageAI
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.garage_motion
  condition: []
  action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.deepstack_object_garage
  mode: parallel
  max: 10
- id: '1616212788722'
  alias: Motioneye - Sidegate - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard-started
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sidegate_motion_detected
  mode: single
- id: '1616212897306'
  alias: Motioneye - Sidegate - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard-ended
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sidegate_motion_detected
  mode: queued
  max: 10
- id: '1616214454392'
  alias: SidegateAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sidegate_motion
  condition: []
  action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.deepstack_object_sidegate
  mode: queued
  max: 10
- id: '1617115271505'
  alias: Motioneye - Garage - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-garage-started
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_motion_detected
    data: {}
  mode: single
- id: '1617115348817'
  alias: Motioneye - Garage - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-garage-ended
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_motion_detected
    data: {}
  mode: single
- id: '1629773116634'
  alias: BackdoorAI
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.backdoor_motion
  condition: []
  action:
  - service: image_processing.scan
    target:
      entity_id: image_processing.deepstack_object_backdoor
    data: {}
  mode: queued
  max: 10
- id: '1629773270589'
  alias: Motioneye - Backdoor - Motion started
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard2-started
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.backdoor_motion_detected
  mode: single
- id: '1629773461364'
  alias: Motioneye - Backdoor - Motion ended
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-backyard2-ended
    allowed_methods:
    - POST
    - PUT
    local_only: false
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.backdoor_motion_detected
  mode: queued
  max: 10
- id: '1635131985239'
  alias: HA_Backup_To_GitHub
  description: push HA configuration to GitHub repo
  trigger:
  - platform: time
    at: '23:23:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/ha_gitpush.sh
  mode: single
- id: '1673200577304'
  alias: Basement Motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.basementlights
    state: 'off'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.basementlights
    metadata: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.basement_off
    metadata: {}
  mode: single
- id: '1675031627562'
  alias: Outdoor Lights Vacation Schedule
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.nigel
      state: not_home
    - condition: state
      entity_id: device_tracker.karlenes_iphone
      state: not_home
    - condition: state
      entity_id: device_tracker.bry
      state: not_home
    - condition: state
      entity_id: alarm_control_panel.north_york_alarm
      state: armed_away
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.backyard_2
      - light.frontyard_2
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.switch1_2
      - switch.switch2_2
      - switch.plug1
      - switch.living_room_lamp
  mode: single
- id: '1691016283007'
  alias: Close Garage Door - Alarm Set To Home.
  description: Check if garage door is open when alarm set to Home. Close if open.
  trigger:
  - platform: state
    entity_id: alarm_control_panel.north_york_alarm
    to: armed_home
  condition:
  - condition: state
    entity_id: cover.garage
    state: open
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.garage
  mode: single
