homeassistant:
  allowlist_external_dirs:
    - /config/images
  media_dirs:
    local: /config/images

# Waste collection
waste_collection_schedule:
  sources:
    - name: toronto_ca
      args:
        street_address: !secret my_address

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sun.sun
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
    event_types:
      - call_service # Don't record service calls

frontend:
  themes: !include_dir_merge_named themes

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.77.0/24

# System Health
system_health:

default_config:

# menubar stuff
hassio:

# Stream
stream:

binary_sensor:
  - platform: template
    sensors:
      nest_connection_status:
        friendly_name: Ring Alarm
        device_class: connectivity
        value_template: "{{ is_state_attr('sensor.north_york_base_station_info', 'commStatus', 'ok') }}"

    # Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "reactive_power"
      state_topic: "shellies/shellyem/emeter/1/reactive_power"
    - name: "pf"
      state_topic: "shellies/shellyem/emeter/1/pf"
    - name: "voltage"
      state_topic: "shellies/shellyem/emeter/1/voltage"
    - name: "total"
      state_topic: "shellies/shellyem/emeter/1/total"
    - name: "total_returned"
      state_topic: "shellies/shellyem/emeter/1/total_returned"
