homeassistant:
  allowlist_external_dirs:
    - /config/images
  media_dirs:
    local: /config/images

# Waste collection
waste_collection_schedule:
  sources:
    - name: toronto_ca
      args:
        street_address: !secret my_address

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
    event_types:
      - call_service # Don't record service calls

frontend:
  themes: !include_dir_merge_named themes

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# System Health
system_health:

default_config:
ios:

# menubar stuff
hassio:

# Stream
stream:

# outdoor cameras (mjpeg and rtsp)
camera:
  - platform: local_file
    file_path: /config/www/deepstack_object_front_door_latest.png
    name: deepstack_latest_frontdoor

# Deepstack AI
image_processing:
  - platform: deepstack_object
    ip_address: !secret deepstack_host
    port: 5000
    timeout: 10
    save_file_folder: /config/www
    save_file_format: png
    save_timestamped_file: True
    always_save_latest_file: True
    targets:
      - target: person
        confidence: 50
      - target: car
        confidence: 15
      - target: vehicle
        confidence: 60
      - target: dog
        confidence: 40
    source:
      - entity_id: camera.front_door

template:
  - sensor:
      - name: "Outdoor Humidity"
        unit_of_measurement: "%"
        device_class: humidity
        state_class: measurement
        state: >-
          {{ state_attr('weather.home','humidity') }}

binary_sensor:
  - platform: template
    sensors:
      nest_connection_status:
        friendly_name: Ring Alarm
        device_class: connectivity
        value_template: "{{ is_state_attr('sensor.north_york_base_station_info', 'commStatus', 'ok') }}"

    # Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
# weather: !include weather.yaml
