- platform: template
  name: "Weather Toronto"
  condition_template: "{{ states('weather.toronto_forecast') }}"
  temperature_template: "{{ state_attr('weather.home', 'temperature') | round(0) }}"
  humidity_template: "{{ state_attr('weather.home', 'humidity') | round(0) }}"
  forecast_template: >
    {% set ns = namespace(z = []) %}
    {% for x in state_attr('weather.toronto_forecast', 'forecast') %}
      {% set ns.z = ns.z +
      [{
        'condition': x.condition,
        'precipitation': x.precipitation_probability,
        'temperature': x.temperature | default(0),
        'templow': x.templow | round(0),
        'datetime': x.datetime
        }] %}
     {% endfor %}
     {{ ns.z }}
